### ISSUE TITLE
Publish to NPM ?

### ISSUE THREAD

**Issue by RakanNimer** [Instabug/instabug-reactnative#1]
Hey ! 

Thanks for the great work on this module and instabug. 
Could you publish this package to npm so we can freeze the package version in our build ?

Cheers !

**Comment by DevHossamHassan** [comment]
Hello @RakanNimer 
Thank you so much for your suggestion.
and we really sorry for the delay, and finally we did publish `instabug-reactnative` to npm 🎉 
So, You can install it anytime via `npm`
Thank you for your patience
