### ISSUE TITLE
strip-frameworks.sh: No such file or directory

### ISSUE THREAD

**Issue by SudoPlz** [Instabug/instabug-reactnative#104]
I believe you forgot to add `InstabugCore.framework` to the iOS project, and so we get the following error.

I can't make 2.1.1 work on iOS, thank you.

**Comment by SudoPlz** [comment]
False flag, I believe that was just me upgrading from an older version of instabug-reactnative.

I unlinked the project, deleted it, installed, linked again and it worked.

**Comment by SudoPlz** [comment]
That was because the new `unlink.rb` file did not work with the old link setup.

I downloaded [the old unlink.rb file](https://raw.githubusercontent.com/Instabug/instabug-reactnative/v2.0.19/unlink.rb), renamed it to `unlinkOld.rb` and pasted it on the root dir of instabug-reactnative, then run `ruby node_modules/instabug-reactnative/unlinkOld.rb;ruby node_modules/instabug-reactnative/link.rb` and then it worked.

**Comment by watadarkstar** [comment]
What I did to resolve this issue that @SudoPlz talks about:
```
/Users/sudoplz/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object_list.rb:218:in `block in perform_deletion_operations': undefined method `remove_referrer' for nil:NilClass (NoMethodError)
	from /Users/sudoplz/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object_list.rb:216:in `each'
	from /Users/sudoplz/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object_list.rb:216:in `perform_deletion_operations'
	from /Users/sudoplz/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object_list.rb:113:in `delete'
	from node_modules/instabug-reactnative/unlink.rb:31:in `<main>'
```

I downgraded:
```
yarn add instabug-reactnative@2.0.9
react-native unlink instabug-reactnative
```
