### ISSUE TITLE
Instabug crashes on start, IOS simulator, after reload cmd +r

### ISSUE THREAD

**Issue by zivchen** [Instabug/instabug-reactnative#106]
*** Doesnt happen every time
If it happens, its only after reload cmd + r

react-native-cli: 2.0.1
react-native: 0.50.4
MacBook Pro High Sierra
IOS simulator - iphone 6

Exception '*** -[NSOperationQueue addOperation:]: operation is finished and cannot be enqueued' was thrown while invoking startWithToken on target Instabug with params (
    XXXXXXXXXXXXXXXXXXXXXXXXXXX,
    1
)
callstack: (
	0   CoreFoundation                      0x000000010972b1ab __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000107b3cf41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010979fcb5 +[NSException raise:format:] + 197
	3   Foundation                          0x000000010754d464 __addOperations + 1099
	4   InstabugCore                        0x000000010739f5fa -[IBGIntializationManager addOperation:] + 79
	5   Instabug                            0x000000010726826b +[Instabug startWithToken:invocationEvent:] + 342
	6   edocate                             0x000000010626ba24 -[InstabugReactBridge startWithToken:invocationEvent:] + 100
	7   CoreFoundation                      0x00000001096af49c __invoking___ + 140
	8   CoreFoundation                      0x00000001096af370 -[NSInvocation invoke] + 320
	9   CoreFoundation                      0x00000001096c7d56 -[NSInvocation invokeWithTarget:] + 54
	10  edocate                             0x0000000105e6004c -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2796
	11  edocate                             0x0000000105ef69c2 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 786
	12  edocate                             0x0000000105ef64ef _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 127
	13  edocate                             0x0000000105ef6469 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25
	14  libdispatch.dylib                   0x000000010e5bd273 _dispatch_call_block_and_release + 12
	15  libdispatch.dylib                   0x000000010e5be2b5 _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x000000010e5c8496 _dispatch_main_queue_callback_4CF + 1260
	17  CoreFoundation                      0x00000001096edee9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	18  CoreFoundation                      0x00000001096b2592 __CFRunLoopRun + 2402
	19  CoreFoundation                      0x00000001096b19b9 CFRunLoopRunSpecific + 409
	20  GraphicsServices                    0x0000000111fcc9c6 GSEventRunModal + 62
	21  UIKit                               0x000000010c3525e8 UIApplicationMain + 159
	22  edocate                             0x0000000105dcb11f main + 111
	23  libdyld.dylib                       0x000000010e632d81 start + 1
)
reactConsoleErrorHandler @ index.bundle:12039
console.(anonymous function) @ index.bundle:55099
console.error @ index.bundle:44984
logToConsole @ index.bundle:18326
logIfNoNativeHook @ index.bundle:18309
__callFunction @ index.bundle:7131
(anonymous) @ index.bundle:6961
__guard @ index.bundle:7102
callFunctionReturnFlushedQueue @ index.bundle:6960
t @ RNDebuggerWorker.js:1

**Comment by SudoPlz** [comment]
Hey my friend, that is the same issue as https://github.com/Instabug/instabug-reactnative/issues/105, just so that you know.

**Comment by salmatarzi** [comment]
@zivchen The fix for this issue is now released, kindly upgrade to v2.1.2

**Comment by zivchen** [comment]
@salmatarzi Thanks
