### ISSUE TITLE
(iOS) Use of undeclared identifiers

### ISSUE THREAD

**Issue by zoontek** [Instabug/instabug-reactnative#108]
Hi everyone!

I'm trying to setup this library in a React Native 0.51 project.
I tried the official way to link it, a manual way, adding the SDK with Cocoapods, etc and always have the same errors.

<img width="1406" alt="screen shot 2017-12-28 at 11 44 58" src="https://user-images.githubusercontent.com/1902323/34408754-ec24d4fc-ebc5-11e7-918a-4705dfd37081.png">

Do you encounter them? Thanks!

**Comment by salmatarzi** [comment]
Hi @zoontek 

I will have a release with this fix in a few. I'll keep you posted.

**Comment by salmatarzi** [comment]
@zoontek The release is now out, please update by using 

`npm install instabug-reactnative` 😊

**Comment by zoontek** [comment]
@sebirdman Thanks, it worked!
