### ISSUE TITLE
Release v1.0.5 does not contain any changes from previous version

### ISSUE THREAD

**Issue by yloeza** [Instabug/instabug-reactnative#11]
Some bug fixes got merged into master but the release v1.0.5 does not contains any of those fixes.

Seems like the only change this version contains is just the version bump in the `package.json` file.

@DevHossamHassan Wondering if you can release a fix for this any time soon?

**Comment by DevHossamHassan** [comment]
Hey @yloeza,
The release v1.0.5 contains all those hotfixes.
Please delete `instabug-reactnative` old version and try to install the latest one. 
I could send you a sample app uses v1.0.5 contains the hotfixes, If you want.

**Comment by yloeza** [comment]
@DevHossamHassan Confirmed, v1.0.5 look good now, not sure what happened before. Closing this issue.
