### ISSUE TITLE
Invoking dialog changes status bar color from white to black

### ISSUE THREAD

**Issue by adambom** [Instabug/instabug-reactnative#110]
My app uses the status bar style "light-content". When I invoke the dialog, and then dismiss it, the status bar gets changed from light to dark. This happens regardless of which theme I set for instabug:

Before:
<img width="378" alt="screen shot 2018-01-03 at 12 48 53 pm" src="https://user-images.githubusercontent.com/294597/34539221-8620ba68-f084-11e7-9d2f-fe59167efd1f.png">

After:
<img width="373" alt="screen shot 2018-01-03 at 12 49 07 pm" src="https://user-images.githubusercontent.com/294597/34539231-8ad557da-f084-11e7-89ee-5c7d2abd83f7.png">

**Comment by adambom** [comment]
FYI, if anyone else is experiencing this problem, the workaround I found is to add a global post invocation handler like so:

```javascript
import Instabug from 'instabug-reactnative';
import { StatusBar } from 'react-native';


Instabug.setPostInvocationHandler(() => {
  StatusBar.setBarStyle('light-content');
});
```

**Comment by ZiadAyman** [comment]
hey @adambom 
Apologies for checking this late! 
Thanks for the workaround, we'll definitely need to be fixing this from our side. 

You mind telling me what instabug-react native SDK version you are on?

**Comment by jamesreggio** [comment]
@kamelnabil Was this fixed?
