### ISSUE TITLE
Add ios permissions instructions to documentation

### ISSUE THREAD

**Issue by adambom** [Instabug/instabug-reactnative#113]
For ios, the sdk requires changes to info.plist privacy settings. The following is included in the ios sdk instructions, but it's not obvious that this is also required when using the react-native sdk. I'd suggest adding this text to the README:

# Microphone and Photo Library Usage Description

Instabug needs access to the microphone and photo library to be able to let users add audio and video attachments. Starting from iOS 10, apps that don’t provide a usage description for those 2 permissions would be rejected when submitted to the App Store.

For your app not to be rejected, you’ll need to add the following 2 keys to your app’s info.plist file with text explaining to the user why those permissions are needed:

`NSMicrophoneUsageDescription`
`NSPhotoLibraryUsageDescription`

If your app doesn’t already access the microphone or photo library, we recommend using a usage description like:

"<app name> needs access to the microphone to be able to attach voice notes."
"<app name> needs access to your photo library for you to be able to attach images."

The permission alert for accessing the microphone/photo library will NOT appear unless users attempt to attach a voice note/photo while using Instabug.

**Comment by ZiadAyman** [comment]
hey @adambom 
Thank you so much for reaching out with this. We'll be adding this shortly!

Thanks for notifying us one more time :)
