### ISSUE TITLE
Changes needed for gradle 3.0.1 compatibility

### ISSUE THREAD

**Issue by pacamara** [Instabug/instabug-reactnative#116]
Some minor changes are needed for gradle 3.0.1 compatibility: in android/build.gradle:
* Remove the `buildToolsVersion`, gradle now specifies a default and the current value conflicts with that.
* Declare dependencies using `api` not `compile` per https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#new_configurations

We are currently hacking these changes with a script in status.im, and would rather it is fixed upstream. Thanks!

Parent issue: https://github.com/status-im/status-react/issues/3037

**Comment by ZiadAyman** [comment]
Hey @pacamara 
Please accept my apologies on the late reply here! 
We are on it.

**Comment by ZiadAyman** [comment]
Can you try to install please this branch using
 npm install https://github.com/Instabug/instabug-reactnative#hotfix/gradle_3.0.1
and tell me if the issue is fixed or not?

**Comment by pacamara** [comment]
@ZiadAyman Thanks! That leads to a build failure with
```
> Could not resolve com.instabug.library:instabug:4.9.0.3-SNAPSHOT.
  Required by:
      project :app > project :instabug-reactnative
   > Could not resolve com.instabug.library:instabug:4.9.0.3-SNAPSHOT.
      > Could not get resource 'http://139.162.11.12:8081/artifactory/libs-release-local/com/instabug/library/instabug/4.9.0.3-SNAPSHOT/instabug-4.9.0.3-SNAPSHOT.pom'.
         > Could not GET 'http://139.162.11.12:8081/artifactory/libs-release-local/com/instabug/library/instabug/4.9.0.3-SNAPSHOT/instabug-4.9.0.3-SNAPSHOT.pom'. Received status code 409 from server: Conflict
```
(on a fresh checkout, and with instabug removed from .gradle and .m2 directories). Any ideas?

**Comment by viniciusvieir** [comment]
I got the same error. Any solutions?

**Comment by Korazy** [comment]
Hey @viniciusvieir @pacamara 

Can you go to the project level build.gradle file which they can find in this path YourProjectName/android/build.gradle and add these lines:

maven {
            // TODO add this only if interested in getting SNAPSHOT releases
            url "https://oss.sonatype.org/content/repositories/snapshots"
}

Let me know if it works for you :)
