### ISSUE TITLE
[Android] FileNotFoundException upon bug upload

### ISSUE THREAD

**Issue by edcrampin** [Instabug/instabug-reactnative#119]
Hi,

Upon installing this library within my RN application, I managed to get everything working fine on iOS however on Android, upon the submission of bug reports, I'm receiving a java.io.FileNotFoundException when it seems to try and fetch the screenshot of the bug report. Stack trace below:

```
W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.*.*/files/instabug/attachments/bug_1518427383402_.jpg (No such file or directory)
W/System.err:     at java.io.FileInputStream.open(Native Method)
W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:146)
W/System.err:     at com.instabug.library.util.BitmapUtils.compressBitmapAndSave(BitmapUtils.java:94)
W/System.err:     at com.instabug.bug.d.d(LiveBugManager.java:198)
W/System.err:     at com.instabug.bug.d.b(LiveBugManager.java:39)
W/System.err:     at com.instabug.bug.d$1.run(LiveBugManager.java:133)
W/System.err:     at java.lang.Thread.run(Thread.java:761)
```

**Comment by edcrampin** [comment]
Looking in to this a little more, it appears the `bug_1518427383402_.jpg` that could not be found is actually located under:
`/storage/emulated/0/Android/data/com.*.*/files/instabug/`
instead of
`/storage/emulated/0/Android/data/com.*.*/files/instabug/attachments`

**Comment by ZiadAyman** [comment]
hey @edcrampin do you mind clearing your app data and give it another try? Let me know if you are still experiencing the same problem after it please.

**Comment by edcrampin** [comment]
Hi @ZiadAyman still no luck, having even tried installing on different devices.

It manages to find the image during the preview screen of the bug, where the user can enter in details of the bug, but once submit is clicked it looks within the `instabug/attachments` directory but the file is not there, but instead the `instabug` directory.

**Comment by ZiadAyman** [comment]
Do you mind telling me the react native SDK version you are currently on?

**Comment by edcrampin** [comment]
Currently running on 0.51.0!

**Comment by ZiadAyman** [comment]
I am sorry if I was not clear, I am trying to know your `instabug react-native` SDK version.

**Comment by ZiadAyman** [comment]
Thank you! Will check this and get back to you.

**Comment by ZiadAyman** [comment]
Can I have your instabug integration code please? Would be extremely helpful for us here.

**Comment by edcrampin** [comment]
Inside my `getPackages`, in MainApplication.java:
```
new RNInstabugReactnativePackage.Builder("--removed--",MainApplication.this)
        .setInvocationEvent("none")
        .setPrimaryColor("#FF0099")
        .build(),
```

Inside of my root React Native element's constructor I have:
```
	Instabug.startWithToken('--MY IOS TOKEN--', Instabug.invocationEvent.none)
	Instabug.setPrimaryColor(processColor('#ff0099'))
	Instabug.setIntroMessageEnabled(false)
	Instabug.setPromptOptionsEnabled(false, true, true)
	Instabug.setChatNotificationEnabled(false)
	Instabug.setViewHierarchyEnabled(false)
```

And then to invoke Instabug I just have a TouchableOpacity around an Icon that runs `Instabug.invoke()`

**Comment by ZiadAyman** [comment]
Thank you so much for collaborating here @edcrampin 
We are working on it, will get back to you once everything is in place.

**Comment by ZiadAyman** [comment]
Hey @edcrampin 
We have been trying to reproduce this issue with no luck. Even with your exact integration steps everything is fine. So, do you mind if you can send a sample app please that has the problem so we can reproduce and debug this from our side?

**Comment by imVinayPandya** [comment]
@ZiadAyman i have found the same bug for instabug cordova SDK https://github.com/Instabug/instabug-cordova/issues/53.

**Comment by Korazy** [comment]
@edcrampin i'll go ahead and close this issue. Please feel free to reopen this issue if it still exists for you on the latest version :)
