### ISSUE TITLE
Invoking introMessage once per session?

### ISSUE THREAD

**Issue by natasha-robarge** [Instabug/instabug-reactnative#121]
Hey, I just have a question- how can I invoke the introMessage popup only once in React Native?

I noticed that in the instabug-iOS library you guys have a way of doing this as specified in this ticket: https://github.com/Instabug/Instabug-iOS/issues/66

Is there any place I can look for a way of doing this in the documentation?
Thank you.

**Comment by ZiadAyman** [comment]
Hey @natasha-robarge 
Apologies for the late reply on this. 

Yes you can indeed. 
Set `Instabug.setIntroMessageEnabled(false)` and then invoke the API `Instabug.showIntroMessage();` to invoke the SDK. 

You can find all the details about this in out docs [here](https://docs.instabug.com/docs/react-native-invocation)
