### ISSUE TITLE
iOS issue: Linking fails if project doesn't have a target named like the project

### ISSUE THREAD

**Issue by ricbermo** [Instabug/instabug-reactnative#123]
Hi there,
I have `MyAwesomeProject` with 2 targets, staging and prod. As soon as I run `react-native link` the ruby script throws an error because I don't have a target named `MyAwesomeProject`.

Solution #1: Add a target named `MyAwesomeProject`.
Solution #2: in `link.rb`
```ruby
default_target = project.targets.find { |target| target.to_s == default_target_name } || project.targets.first
```
Would love to send a PR.
Thanks in advance

**Comment by Korazy** [comment]
Hey @ricbermo , this is currently planned for the next release. I will update you once it's resolved.

**Comment by ricbermo** [comment]
@Korazy I'm closing the issue. Let me know if I should re-open it. Thank you!

**Comment by Korazy** [comment]
It's no worries at all, happy to help.
