### ISSUE TITLE
Swipe doesn't work was invocation event

### ISSUE THREAD

**Issue by ricbermo** [Instabug/instabug-reactnative#124]
Not sure what else to add here, as the title is pretty self-explanatory.

My config:
```java
new RNInstabugReactnativePackage.Builder(BuildConfig.INSTABUG_APP_ID,MainApplication.this)
							.setInvocationEvent("swipe")
							.setPrimaryColor("#1D82DC")
							.build(),
```

I haven't tried on iOS since I don't have one iDevice to test.

**Comment by Korazy** [comment]
Hi @ricbermo, please let me check this and get back to you, thanks for pointing it out.

**Comment by Korazy** [comment]
@ricbermo can you please override this method in the MainActivity class and let me know how it goes?
``    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        InstabugTrackingDelegate.notifyActivityGotTouchEvent(ev, this);
        return super.dispatchTouchEvent(ev);
    }``

**Comment by ricbermo** [comment]
@Korazy I'm getting errors. I guess I need to import something but not sure what.
1. Override error: Method does not override method from its superclass.
2. 
![screen shot 2018-03-14 at 10 28 29 am](https://user-images.githubusercontent.com/2601363/37412256-91366306-2772-11e8-8cc3-cf186fdfc9af.png)
`MainActivity.java`
```java
package com.project.id;
import android.os.Bundle;
import com.facebook.react.ReactActivity;
import org.devio.rn.splashscreen.SplashScreen;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "MyAwesomeProj";
    }


    /*
     * this is for https://github.com/crazycodeboy/react-native-splash-screen
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        SplashScreen.show(this);
        super.onCreate(savedInstanceState);
    }

    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        InstabugTrackingDelegate.notifyActivityGotTouchEvent(ev, this);
        return super.dispatchTouchEvent(ev);
    }
}
```

**Comment by Korazy** [comment]
@ricbermo can you please try importing the following?
``import android.view.MotionEvent;
import com.instabug.library.InstabugTrackingDelegate;``

**Comment by ricbermo** [comment]
@Korazy it did work. Thank you so much for your assistance!

**Comment by Korazy** [comment]
@ricbermo Awesome, happy to help! Please get back to us if you need help with anything else :)
