### ISSUE TITLE
SIGTRAPI BGUserStepsImagesLocalAttachment

### ISSUE THREAD

**Issue by SudoPlz** [Instabug/instabug-reactnative#125]
Hey there,

today I received this in our bug reporter:
## Steps to reproduce
1) Invoke instabug from screenshot invocation in iOS
2) Annotate on image (I wrote the word test with annotation lines)
3) Wrote the word Test
4) Pushed the send button
5) App crashed, and I received this stacktrace

I managed to make this happen a couple of times but it doesn't ALWAYS happen.

## Stacktrace

	SIGTRAP
	    /usr/lib/system/libdispatch.dylib _dispatch_group_leave$VARIANT$mp
	    Frameworks/InstabugCore.framework/InstabugCore __76-[IBGUserStepsImagesLocalAttachment prepareAttachmentAndSaveWithCompletion:]_block_invoke
	    Frameworks/InstabugCore.framework/InstabugCore __73-[IBGUserStepsImagesLocalAttachment prepareAttachmentPathWithCompletion:]_block_invoke_2
	    Frameworks/InstabugCore.framework/InstabugCore -[IBGUserStepsImagesLocalAttachment compressFiles:withCompletion:]
	    Frameworks/InstabugCore.framework/InstabugCore __73-[IBGUserStepsImagesLocalAttachment prepareAttachmentPathWithCompletion:]_block_invoke
	    Frameworks/InstabugCore.framework/InstabugCore -[IBGUserStepsLogger loadUserStepsWithContext:sessionId:completionHandler:]
	    Frameworks/InstabugCore.framework/InstabugCore __43-[IBGDALService readASync:completionBlock:]_block_invoke_3
	    Frameworks/CoreData.framework/CoreData _developerSubmittedBlockToNSManagedObjectContextPerform
	    /usr/lib/system/libdispatch.dylib __dispatch_client_callout
	    /usr/lib/system/libdispatch.dylib __dispatch_queue_barrier_sync_invoke_and_complete
	    Frameworks/CoreData.framework/CoreData -[NSManagedObjectContext performBlockAndWait:]
	    Frameworks/InstabugCore.framework/InstabugCore __43-[IBGDALService readASync:completionBlock:]_block_invoke_2
	    /usr/lib/system/libdispatch.dylib __dispatch_call_block_and_release
	    /usr/lib/system/libdispatch.dylib __dispatch_client_callout
	    /usr/lib/system/libdispatch.dylib __dispatch_queue_serial_drain$VARIANT$mp
	    /usr/lib/system/libdispatch.dylib __dispatch_queue_invoke$VARIANT$mp
	    /usr/lib/system/libdispatch.dylib __dispatch_root_queue_drain_deferred_wlh$VARIANT$mp
	    /usr/lib/system/libdispatch.dylib __dispatch_workloop_worker_thread$VARIANT$mp
	    /usr/lib/system/libsystem_pthread.dylib __pthread_wqthread

## Details:
**instabug-reactnative**": "2.7.0,
**react-native**": "0.53.3,
**react**": "16.2.0,
**Device**: iPad Air 2 physical device
**iOS** 11.2.6
**Build** Production

**Comment by Korazy** [comment]
Hey @SudoPlz, thanks for pointing this out. Please let me check it and get back to you.

**Comment by Korazy** [comment]
@SudoPlz Can you please send me the device memory and storage at the time of the crash?

**Comment by SudoPlz** [comment]
For sure my friend, there:

    batteryLevel: 0.7900000214576721
    charging: 0
    freeDisk: 110911963136
    freeMemory: 33046528
    totalMemory: 1583923200
    jailbroken: false
    locale: en_GR
    manufacturer: Apple
    model: iPad Air 2
    modelNumber: J81AP
    orientation: portrait
    osName: iOS
    osVersion: 11.2.6
    timezone: null

**Comment by Korazy** [comment]
Thanks! I'll pass it on and get back to you.

**Comment by SudoPlz** [comment]
And that issue was created and discovered by me on one of my devices, so let me know if you need anything else.

**Comment by Korazy** [comment]
Awesome, thanks again!

**Comment by Kmohamed** [comment]
@SudoPlz Hello my friend,
Till now you are opening three issues related to iOS so for 
we already fixed all issues and will be included in the next Sunday release except this one. so could you please help me to reproduce this issue by integrating this [custom build](https://github.com/Instabug/instabug-reactnative/tree/custom/ios_logs)  and try to crash the app and send me all logs.

**Comment by Kmohamed** [comment]
@SudoPlz one more thing could you please cal this method
    `[Instabug setSDKDebugLogsLevel:IBGSDKDebugLogsLevelVerbose];`

**Comment by SudoPlz** [comment]
Hi @Kmohamed 
I'm using react-native, am I supposed to add that code to the native side?

**Comment by Kmohamed** [comment]
Yes please.

**Comment by Kmohamed** [comment]
@SudoPlz any updates ?

**Comment by SudoPlz** [comment]
I integrated that custom build, and added the code, but I can't reproduce the issue..
¯\_(ツ)_/¯

You should probably add logs to the main sdk to get logs and info about crashes caused by instabug itself permanently.

**Comment by Kmohamed** [comment]
@SudoPlz sure I will and Thanks a lot for your support my friend.

**Comment by SudoPlz** [comment]
Let me know if that helps: 

![image](https://user-images.githubusercontent.com/3070948/39154708-dfb04506-4757-11e8-8ba5-588c286e9021.png)

Looks like the user started typing something, then hid the window and the crash happened.

**Comment by Kmohamed** [comment]
@SudoPlz I am not aware of this view structure 
Could you send to me a stacktrace ?

**Comment by SudoPlz** [comment]
Oh the stacktrace is still the exact same as the one in the first message https://github.com/Instabug/instabug-reactnative/issues/125#issue-305100969
nothing changed, I just added a couple of breadcrumbs that we received along with the stacktrace.

Think of it as repro steps coming from bugsnag.
This is not a view structure, it's a series of events starting from the newest to the oldest.

**Comment by Kmohamed** [comment]
@SudoPlz Thanks a lot for the info I will take a look on it

**Comment by Kmohamed** [comment]
@SudoPlz I succeed to reproduce the issue and it will be included in the next release (Next Sunday)
Thanks  a lot for your support.

**Comment by SudoPlz** [comment]
You're the best, thanks @Kmohamed
