### ISSUE TITLE
NSInvalidArgumentException IBGMethodsLogger

### ISSUE THREAD

**Issue by SudoPlz** [Instabug/instabug-reactnative#127]
Hey there,

another one that came in from one of our production devices.

## Stacktrace

    NSInvalidArgumentException *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[3] 
        Frameworks/CoreFoundation.framework/CoreFoundation ___exceptionPreprocess
        /usr/lib/libobjc.A.dylib _objc_exception_throw
        Frameworks/CoreFoundation.framework/CoreFoundation __CFThrowFormattedException
        Frameworks/CoreFoundation.framework/CoreFoundation -[__NSPlaceholderArray initWithObjects:count:]
        Frameworks/CoreFoundation.framework/CoreFoundation +[NSArray arrayWithObjects:count:]
        Frameworks/CoreFoundation.framework/CoreFoundation -[NSDictionary allValues]
        Frameworks/InstabugCore.framework/InstabugCore -[IBGMethodsLogger allMethodsLog]
        Frameworks/InstabugCore.framework/InstabugCore -[IBGMethodsLogger dictionaryValue]
        Frameworks/InstabugCore.framework/InstabugCore -[IBGAnalytics dictionaryValue]
        Frameworks/InstabugCore.framework/InstabugCore -[IBGCache writeModels:toPath:]
        Frameworks/InstabugCore.framework/InstabugCore __22-[IBGCache persistAll]_block_invoke
        /usr/lib/system/libdispatch.dylib __dispatch_client_callout
        /usr/lib/system/libdispatch.dylib __dispatch_continuation_pop$VARIANT$armv81
        /usr/lib/system/libdispatch.dylib __dispatch_source_invoke$VARIANT$armv81
        /usr/lib/system/libdispatch.dylib __dispatch_main_queue_callback_4CF$VARIANT$armv81
        Frameworks/CoreFoundation.framework/CoreFoundation ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
        Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopRun
        Frameworks/CoreFoundation.framework/CoreFoundation _CFRunLoopRunSpecific
        PrivateFrameworks/GraphicsServices.framework/GraphicsServices _GSEventRunModal
        Frameworks/UIKit.framework/UIKit _UIApplicationMain
        AcuityApp/main.m:16:12 main
        /usr/lib/system/libdyld.dylib _start

## Details:
**instabug-reactnative**": "2.7.0,
**react-native**": "0.53.3,
**react**": "16.2.0,
**Device**: iPhone 8 Plus physical device
**iOS** 11.2.1
**Build** Production

batteryLevel 0.7099999785423279
charging 0
freeDisk 19959369728
freeMemory 114393088
totalMemory 2679390208
jailbroken false
manufacturer Apple
modelNumber D211AP
orientation portrait

**Comment by Kmohamed** [comment]
@SudoPlz This also will be fixed in the next release.

**Comment by Kmohamed** [comment]
@SudoPlz Fixed in the latest version.
