### ISSUE TITLE
NSInvalidArgumentException Cannot read file at file ...

### ISSUE THREAD

**Issue by SudoPlz** [Instabug/instabug-reactnative#129]
Hey there,

another one that came in from one of our production devices.

## Stacktrace

    NSInvalidArgumentException Cannot read file at file:///var/mobile/Containers/Data/Application/579FFC04-D4CF-45DC-AB73-61DD567EF198/Library/IBGTemp/2018031601580194353508 
        Frameworks/CoreFoundation.framework/CoreFoundation ___exceptionPreprocess
        /usr/lib/libobjc.A.dylib _objc_exception_throw
        Frameworks/CFNetwork.framework/CFNetwork -[__NSURLBackgroundSession validateUploadFile:]
        Frameworks/CFNetwork.framework/CFNetwork -[__NSURLBackgroundSession _onqueue_uploadTaskForRequest:uploadFile:bodyData:completion:]
        Frameworks/CFNetwork.framework/CFNetwork ___80-[__NSURLBackgroundSession uploadTaskForRequest:uploadFile:bodyData:completion:]_block_invoke
        Frameworks/CFNetwork.framework/CFNetwork ___68-[__NSURLBackgroundSession performBlockOnQueueAndRethrowExceptions:]_block_invoke
        /usr/lib/system/libdispatch.dylib __dispatch_client_callout
        /usr/lib/system/libdispatch.dylib __dispatch_queue_barrier_sync_invoke_and_complete
        Frameworks/CFNetwork.framework/CFNetwork -[__NSURLBackgroundSession performBlockOnQueueAndRethrowExceptions:]
        Frameworks/CFNetwork.framework/CFNetwork -[__NSURLBackgroundSession uploadTaskForRequest:uploadFile:bodyData:completion:]
        Frameworks/InstabugCore.framework/InstabugCore -[IBGServerDataRequest sessionDataTaskWithRawRequest:]
        Frameworks/InstabugCore.framework/InstabugCore __60-[IBGServerDataRequest prepareRequestWithCompletionHandler:]_block_invoke
        Frameworks/InstabugCore.framework/InstabugCore __48-[IBGDiskIOManager writeData:toFile:completion:]_block_invoke
        /usr/lib/system/libdispatch.dylib __dispatch_call_block_and_release
        /usr/lib/system/libdispatch.dylib __dispatch_client_callout
        /usr/lib/system/libdispatch.dylib __dispatch_queue_concurrent_drain
        /usr/lib/system/libdispatch.dylib __dispatch_queue_invoke$VARIANT$mp
        /usr/lib/system/libdispatch.dylib __dispatch_queue_override_invoke$VARIANT$mp
        /usr/lib/system/libdispatch.dylib __dispatch_root_queue_drain
        /usr/lib/system/libdispatch.dylib __dispatch_worker_thread3
        /usr/lib/system/libsystem_pthread.dylib __pthread_wqthread
        /usr/lib/system/libsystem_pthread.dylib _start_wqthread

## Details:
**instabug-reactnative**": "2.7.0,
**react-native**": "0.53.3,
**react**": "16.2.0,
**Device**: iPhone 6 Plus physical device
**iOS** 11.2.6
**Build** Production

batteryLevel 0.6600000262260437
freeDisk 46960640
freeMemory 28983296
totalMemory 1728970752

**Comment by Kmohamed** [comment]
@SudoPlz This also will be fixed in the next release.

**Comment by Kmohamed** [comment]
@SudoPlz Fixed in the latest version.
