### ISSUE TITLE
addFileAttachment function is missing in the JS module

### ISSUE THREAD

**Issue by fangpenlin** [Instabug/instabug-reactnative#130]
`addFileAttachment` function is defined in the native iOS module

https://github.com/Instabug/instabug-reactnative/blob/5bfd6fab7d2b0b4da3e97d85af9c28877191df8b/ios/RNInstabug/InstabugReactBridge.m#L250-L252

but not defined in the index.js JS module

**Comment by Korazy** [comment]
Hey @fangpenlin, thanks for reporting this. We'll check it from our side and get back to you!

**Comment by Korazy** [comment]
After checking this, we'll definitely be adding it to our next release.
