### ISSUE TITLE
Can't build app with instabug

### ISSUE THREAD

**Issue by yevhenjl** [Instabug/instabug-reactnative#133]
Building app was broken with error:
`
> Task :app:generateBundledResourcesHashRelease 
cbd10a94ca2fddb889852d14835614a5cf1578c76203a8586a733f3a1c341a98

warning: string 'instabug_str_dismiss' has no default translation.
warning: string 'instabug_str_record_audio' has no default translation.
warning: string 'instabug_str_survey_counter' has no default translation.
warning: string 'instabug_str_survey_thanks' has no default translation.
warning: string 'instabug_str_survey_thanks_msg' has no default translation.
warning: string 'instabug_str_take_survey' has no default translation.
warning: string 'instabug_str_welcome_feedback' has no default translation.
warning: string 'instabug_str_welcome_feedback_msg' has no default translation.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
`

My android/app/build.gradle:
`
...
compileSdkVersion 27
buildToolsVersion "27.0.1"
...

dependencies {
    compile project(':instabug-reactnative')
    compile project(':react-native-video')
    compile project(':react-native-onesignal')
    compile project(':react-native-device-info')
    compile (project(':react-native-camera')) {
           exclude group: "com.google.android.gms"
     }
    compile project(':react-native-fs')
    compile project(':react-native-code-push')
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:27.0.1"
    compile "com.android.support:exifinterface:27.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
`

**Comment by ZiadAyman** [comment]
hey @yevhenjl We are currently checking this for you and we'll get back asap! Thanks for reporting it.

**Comment by ianataffinity** [comment]
Getting the same error.

**Comment by normal1ze** [comment]
Getting the same error.

**Comment by normal1ze** [comment]
@ZiadAyman any word on this? I am getting this error too when I try and do a release build. Works fine in debug / emulator. (Android)

**Comment by ZiadAyman** [comment]
@normal1ze We are currently working on a fix for this. Apologies for taking sometime here. Will keep you posted!

**Comment by ianataffinity** [comment]
@ZiadAyman Seems there was a problem with memory in the Garbage Collector when running a release build. I had to increase the memory in the gradle.properties file to fix it:

`org.gradle.jvmargs=-Xmx1536M`

It now seems to build find without the error.

**Comment by ZiadAyman** [comment]
@ianataffinity Perfect. Glad all is going good now and apologies for taking sometime here investigating this!
@normal1ze @yevhenjl let me know please if what @ianataffinity suggested is not working for you.
