### ISSUE TITLE
Add enable/disable support for iOS

### ISSUE THREAD

**Issue by peacechen** [Instabug/instabug-reactnative#135]
The `enable`/`disable` methods currently only work for Android.  It would be helpful to support iOS for true cross-platform code.  Our app has a menu option to enable or disable the shake-to-invoke action since it can be intrusive during regular use.
There's a hacky work-around in #84.  Hoping that Instabug will fix this for all platforms.

**Comment by Korazy** [comment]
Hey @peacechen 

Apologies for the late response. Can you please clarify which disable/enable methods you mean? Just to make sure we're on the same page :)

**Comment by peacechen** [comment]
`Instabug.enable()` and `Instabug.disable()`

**Comment by Korazy** [comment]
@peacechen thanks for the clarification. We'll definitely look into adding that in the future. You can change the invocation method on the fly if that using the APIs [here](https://docs.instabug.com/docs/ios-invocation#section-changing-the-invocation-event) if that helps.

**Comment by peacechen** [comment]
Is `setInvocationEvent` exposed through the JS interface?  I don't see it in the code but maybe I'm missing something.  It's not practical to call native iOS methods from the RN side of the app.

**Comment by Korazy** [comment]
Oh apologies, I got confused and thought this was for a native iOS app. Sorry for that :)

**Comment by peacechen** [comment]
Hoping this has been implemented since the issue was closed.  If not, someone else will likely create a dup since closed issues are less likely to be seen.

**Comment by Korazy** [comment]
@peacechen we've communicated the request to the product team and they're checking the possibility of adding it in the future. If more people open issues regarding this it would be very helpful for us since it would expedite the process even more :)

**Comment by Korazy** [comment]
@peacechen that's a good point. I see most of the issues on Github before anyone else in the team has a chance so it's not a problem, however, since this is the first issue asking for this, it's also a way to gauge how requested the feature is.
