### ISSUE TITLE
<MyApp> is not using the latest version of the SDK. Please update to version to be able to use all the features. View Changelog.

### ISSUE THREAD

**Issue by peacechen** [Instabug/instabug-reactnative#140]
Message links to a changelog. Example:
`https://dashboard.instabug.com/applications/<MyApp>/beta/changelog`

```
Change Log
2.7.1 - March 7, 2018
Upgrade native Android and iOS SDK dependency
setReproStepsMode

2.6.0 - February 19, 2018
- setAutoScreenRecordingEnabled API - setAutoScreenRecordingMaxDuration API
```

Our app is using the latest `instabug-reactnative` 2.8.1.
Will this cause any reporting issues?

**Comment by chadyj** [comment]
I'm also having this problem. Support suggested it could be a cache issue on their end, but I still see the message after a week.

**Comment by Korazy** [comment]
@peacechen @chadyj does the banner still show up? A fix should be in place.

**Comment by peacechen** [comment]
It is still showing
![image](https://user-images.githubusercontent.com/6295083/39706463-2884fd38-51d7-11e8-89bb-43726795f06a.png)

Our app is on Instabug RN 2.9.0.  Haven't had the opportunity to update to 2.11.

**Comment by Korazy** [comment]
hey @peacechen 

I just wanted to confirm if this issue is resolved for you.

**Comment by MaxInMoon** [comment]
Same with the `8.2.2`: 
 > ... is not using the latest version of the SDK. Please update to version to be able to use all the features.

Could we re-open it?
