### ISSUE TITLE
setIntroMessageEnabled not working

### ISSUE THREAD

**Issue by ricbermo** [Instabug/instabug-reactnative#141]
Hello, it looks like `Instabug.setIntroMessageEnabled(false)`
This is what I have

```
"react": "16.2.0",
"react-native": "0.53.3",
"instabug-reactnative": "^2.7.1",
```
```javascript
  constructor() {
    super();
    Instabug.setIntroMessageEnabled(false);
    Instabug.setPromptOptionsEnabled(false, true, true);
    if (Platform.OS === 'ios') {
      const app = base === 'prod' ? env.instabug.prod : env.instabug.beta;
      Instabug.startWithToken(app, Instabug.invocationEvent.twoFingersSwipe);
    }
  }
```
<img width="425" alt="screen shot 2018-04-05 at 12 00 27 pm" src="https://user-images.githubusercontent.com/2601363/38380809-7a878afe-38ca-11e8-9d19-db29897d92ae.png">

**Comment by ricbermo** [comment]
@ZiadAyman @Korazy  I'm sorry to ping you directly but I think this is a very important bug.

**Comment by ZiadAyman** [comment]
Hey @ricbermo 
Please accept our apologies for the late reply on this here! 

So setting the intro message to false using `Instabug.setIntroMessageEnabled(false)` doesn't do the job and you still see the intro message? Is this consistent even if you clear your cache and app data? Let me know if its persistent please so we can double check the API's logic from our side. 

Thanks for the patience and thanks for pinging us directly!

**Comment by ricbermo** [comment]
Hello, @ZiadAyman and thanks for your quick response.
Yes, it is not working even after deleting and reinstalling it (`react-native run-ios`).
I thought this was an iOS-only issue but I noticed is happening on Android also.

**Comment by ZiadAyman** [comment]
@ricbermo Thank you so much for the clarification. 

We'll be running some tests and checking this from our side. I will ping you back here for after findings/fixes.

**Comment by CodyBrouwers** [comment]
Looking for a fix for this as well, thanks!

**Comment by KubaGL** [comment]
Looks like `setIntroMessageEnabled` works fine when it's called after `startWithToken`.

**Comment by Korazy** [comment]
Hey @KubaGL, @CodyBrouwers, @ricbermo 

It would indeed work if its called after `startWithToken`. Most Instabug calls should be done after `startWithToken` is called.
