### ISSUE TITLE
logUserEventWithNameAndParams not working

### ISSUE THREAD

**Issue by chadyj** [Instabug/instabug-reactnative#144]
We are sending events events using:
`Instabug.logUserEventWithName("OnFeedbackButtonClicked")` and `Instabug.logUserEventWithNameAndParams("OnFeedbackButtonClicked",{"key": "value"});` 
but no events are showing in the Dashboard.

Version `2.8.1`.

This is blocking us here https://github.com/status-im/status-react/pull/3807

Reported this issue to support and heard back:
>We faced a problem with the UserEvents and UserAttributes and we are currently working on a fix for it. 
but then haven't heard anything.

Any update?

**Comment by Korazy** [comment]
Hey @chadyj,

I just replied to you on the support channel. The issue with the user attributes should be resolved now, but we’re still working on a fix for the user events. I will keep you updated regarding the progress of the fix.

**Comment by chadyj** [comment]
Hope the fixes are going well? It has been about a month since we tried to get surveys running and we've wasted a lot of time.  

Can you give us update on the timing? If you are working on a fix, then great! It would be useful to know. If this isn't on your radar we can start looking for a replacement. Either way please post an update :-)

**Comment by Korazy** [comment]
Hey @chadyj, please accept my apologies for this delay. The issue on our end is quite complex but the engineering team is hard at work on he fix. It's definitely an important issue to us which is why we're trying to fix it as soon as possible!

**Comment by Korazy** [comment]
Hey @chadyj 

Apologies for the delay, the issue should now be resolved. Please let me know if everything is in place on your end :)
