### ISSUE TITLE
[CRASH]  EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by abrel** [Instabug/instabug-reactnative#152]
Some of my iOS users (iOS 11) are experiencing this crash

```
InstabugCore
queues_cpu_usage_with_name + 380
InstabugCore
queues_cpu_usage_with_name + 340
12 arrow_drop_down
libsystem_pthread.dylib
start_wqthread + 4
```
Instabug-react-native version: 2.9.0

**Comment by Korazy** [comment]
Hey @abrel 

Thanks for pointing that out! Can you please update to the latest version of the SDK and let me know if these crashes still occur?

**Comment by abrel** [comment]
No problem!
I have been in production for 3 days with 2.11.1 so far no crash :)
I will let you know if I see this crash happening again

**Comment by Korazy** [comment]
That's great to hear! Please let us know if the crash happens again. Thank you!
