### ISSUE TITLE
issue conflict build.gradle android

### ISSUE THREAD

**Issue by MatthieuPeyrot** [Instabug/instabug-reactnative#157]
Hi

I got an issue when I update to the last version instabug-reactnative. I was in 2.8.1 and upgrade to 2.11.2. it builds but when I start the app it crashes. Well it's not you who crash it's another module that I use react-native-track-player.
I found a way to fix it , in your build.gradle you add 

```
dependencies {
    compile 'com.facebook.react:react-native:0.20.+'
    compile ('com.instabug.library:instabug:4.13.5'){
        exclude group: 'com.android.support:appcompat-v7' <= this was add in one of your commit 
    }
}
```

i simply change the line where it was before 

```
dependencies {
    compile 'com.facebook.react:react-native:0.20.+'
    compile ('com.instabug.library:instabug:4.13.5'){
        exclude group: 'com.android.support'
    }
}
```

and it's working, i have no issue on the player nor with instabug 
You surely had a reason to add this line. Why did you have to add this ?

**Comment by Sammekl** [comment]
[Same issue as here](https://github.com/Instabug/instabug-reactnative/issues/145)

**Comment by Korazy** [comment]
Hey @Sammekl @MatthieuPeyrot

The reason we exclude the v7 because we have version 27 of it and we didn’t want it to conflict with other dependences that uses older version of the support library v7
