### ISSUE TITLE
'Instabug/Instabug.h' file not found

### ISSUE THREAD

**Issue by YahyaQandel** [Instabug/instabug-reactnative#161]
I have been working for 2 days in this issue, the build always fails and gives me this error on iOS"'Instabug/Instabug.h' file not found" 

attached screenshots for the build log and package.json

![screen shot 2018-06-02 at 11 50 48 pm](https://user-images.githubusercontent.com/8913666/40881251-18906520-66c2-11e8-89d4-feca3ad27cd4.png)
![screen shot 2018-06-02 at 11 51 06 pm](https://user-images.githubusercontent.com/8913666/40881252-18b245f0-66c2-11e8-9a5b-f7ace77aa248.png)
![screen shot 2018-06-03 at 12 32 41 am](https://user-images.githubusercontent.com/8913666/40881387-af1c78c8-66c5-11e8-9a0a-6b1c608675c1.png)
![screen shot 2018-06-03 at 12 32 53 am](https://user-images.githubusercontent.com/8913666/40881388-af4093a2-66c5-11e8-8d07-e23767ca341d.png)

**Comment by Korazy** [comment]
Hey @YahyaQandel 

Thanks for reaching out. Can you please try upgrading to the latest version (2.12.0) and let me know if that works for you?

**Comment by YahyaQandel** [comment]
@Korazy 
Thanks for your reply but unfortunately it doesn't work after i upgraded to 2.12.0  
it succeeds on android but fails on iOS .

**Comment by YahyaQandel** [comment]
any updates ?

**Comment by Korazy** [comment]
@YahyaQandel Apologies for the delay. We were unable to reproduce the issue on our end. Would you be able to send us a sample application contactus@instabug.com so we can debug the issue further?

**Comment by YahyaQandel** [comment]
Finally we found that XCode reads the instabug-reactnative package from inside iOS path
**YOUR_APP/ios/node_modules/instabug-reactnative/ios/Instabug.framework**
 .. image attached 

![screen shot 2018-06-11 at 11 08 11 am](https://user-images.githubusercontent.com/8913666/41222734-1c3d2486-6d68-11e8-8710-0bfe4a6a4325.png)

**Comment by Korazy** [comment]
@YahyaQandel so everything is working fine now?

**Comment by Korazy** [comment]
Please feel free to reopen this issue if you run into it again :)
