### ISSUE TITLE
Crash on iOS8

### ISSUE THREAD

**Issue by djhr** [Instabug/instabug-reactnative#162]
Seems current InstabugCore is not compatible with iOS8

```
dyld: Symbol not found: __os_log_default
  Referenced from: /Users/xxx/Library/Developer/CoreSimulator/Devices/xxx/data/Containers/Bundle/Application/xxx/xxx.app/Frameworks/InstabugCore.framework/InstabugCore (which was built for iOS 9.0)
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.dylib
 in /Users/xxxx/Library/Developer/CoreSimulator/Devices/xxx/data/Containers/Bundle/Application/xxx/xxx.app/Frameworks/InstabugCore.framework/InstabugCore
```

RN Version: 0.55.4
Module version: 2.12.0

Since RN still supports iOS8, would be nice not break the compatibility
> RN Docs:
> Supported operating systems are >= Android 4.1 (API 16) and >= iOS 8.0.

**Comment by Korazy** [comment]
Hey @djhr 

Thanks for reaching out! We don't support iOS 8 unfortunately so that is causing the crash. Sorry for the inconvenience.
