### ISSUE TITLE
Can't upgrade to 2.12.0 ENOTDIR: not a directory

### ISSUE THREAD

**Issue by SudoPlz** [Instabug/instabug-reactnative#163]
Whenever I run

`yarn upgrade instabug-reactnative@2.12.0` I get:

error An unexpected error occurred: "ENOTDIR: not a directory, lstat `'/Users/SudoPlz/Development/App/mobile/node_modules/instabug-reactnative/ios/InstabugCore.framework/IBGActionSheetVC-iPhone.nib/objects-11.0+.nib'".`

Any idea why?

**Comment by Korazy** [comment]
Hey @SudoPlz 

Thanks for reaching out to us with this. We're looking into it and will get back to you as soon as possible!

**Comment by juanamd** [comment]
Still happening on version 2.13.1:

`error An unexpected error occurred: "ENOENT: no such file or directory, copyfile 'C:\\Users\\Juan\\AppData\\Local\\Yarn\\Cache\\v1\\npm-instabug-reactnative-2.13.1-cb01061cf1cab9eac1e08b63e6b62276f8653237\\ios\\InstabugCore.framework\\IBGActionSheetVC-iPhone.nib\\objects-11.0+.nib' -> 'C:\\Users\\Juan\\development\\vixjs\\react-native\\ZeldaAlarm\\node_modules\\instabug-reactnative\\ios\\InstabugCore.framework\\IBGActionSheetVC-iPhone.nib\\objects-11.0+.nib'".`

Running Yarn 1.7 on Windows 10

**Comment by Korazy** [comment]
Hey @SudoPlz @juanamd 

Would it be possible to perhaps get a sample app with this error?

**Comment by SudoPlz** [comment]
@Korazy ☝️

**Comment by SudoPlz** [comment]
Any news with that?

**Comment by Korazy** [comment]
Hey @SudoPlz 

Please accept my apologies for this delay. Our engineers are currently working on a fix for it!

**Comment by salmatarzi** [comment]
@SudoPlz @juanamd I think this could be something related to Yarn, I found a few threads on their github page concerning this issue, I don't know if you've came across them.

https://github.com/yarnpkg/yarn/issues/5275

**Comment by SudoPlz** [comment]
Hmm interesting, but I wonder why it happens only after 2.12 and above.

I'll try `rm -rf node_modules && yarn cache clean && yarn install` and report back.

**Comment by SudoPlz** [comment]
ok I upgraded yarn to 1.7.0 (currently the latest version), then the above command fixed the issue.

Apologies for the trouble.

**Comment by Korazy** [comment]
@SudoPlz Thanks for pointing that out!
