### ISSUE TITLE
setPrimaryColor doesn't work on android

### ISSUE THREAD

**Issue by MatthieuPeyrot** [Instabug/instabug-reactnative#165]
Hi

I try to use the setPromaryColor, it's working on iOS but it doesn't change the color on android. I have de default color. I'm on the version 2.13.0 of instabug-reactnative. Do you have any idea?

**Comment by Korazy** [comment]
Hey @MatthieuPeyrot 

Does this issue also occur on version 2.13.2?

**Comment by MatthieuPeyrot** [comment]
@Korazy yes it does

**Comment by Korazy** [comment]
Do you use setPrimaryColor like the following (Android and iOS require different methods)? 

new RNInstabugReactnativePackage.Builder("75385a1b14b5c9ae7952236338095c96",MainApplication.this)
							.setInvocationEvent("button")
							.setPrimaryColor("#1D82DC")
							.setFloatingEdge("left")
							.setFloatingButtonOffsetFromTop(250)
							.build()

**Comment by Korazy** [comment]
@MatthieuPeyrot thanks for letting us know. We're investigating it now.

**Comment by Korazy** [comment]
We’re currently having trouble reproducing this issue, would you be able to send us a sample application with this issue?

**Comment by Korazy** [comment]
@MatthieuPeyrot are you still facing this issue?

**Comment by Korazy** [comment]
Please feel free to reopen this issue if you run into it again :)
