### ISSUE TITLE
How to set the secured property of a view

### ISSUE THREAD

**Issue by havard024** [Instabug/instabug-reactnative#168]
In the documentation of `Auto Screen Recording` in mentions that you could set the `secured` property of any view to exclude user sensitive data. 

What does it mean to set the `secured` property of any view and how do you do it?

**Comment by Korazy** [comment]
Hey @havard024 

Thanks for reaching out. You can put the following in the `onCreate()` method of the activity after the super class call:
`getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE);`
