### ISSUE TITLE
iOS app crashes after coming back from the background on RN 0.55.4

### ISSUE THREAD

**Issue by Sammekl** [Instabug/instabug-reactnative#172]
After upgrading to the latest stable React Native (0.55.4) our iOS app crashes after coming back from the background. We're using the latest instabug-reactnative version (2.13.3) and tried numerous other versions.

When disabling Instabug, the issue is gone.

I've managed to gather the [crash logs](https://gist.github.com/Sammekl/5a9ed1012e62688b8e376b2a8eb0eb13)

This has a really high priority to us, since we cannot migrate back to the old react native and are urgent to ship out a new release.

**Comment by Korazy** [comment]
Hey @Sammekl 

Thanks for reaching out to us, we're looking into this at the moment and will keep you updated.

**Comment by Sammekl** [comment]
We managed to resolve it by setting the sessionProfiler to false. So there's an issue in your sessionProfiler in combination with the new React Native

**Comment by Korazy** [comment]
Thanks for letting us know! Would you be able to clean the derived data and clean the project then try again?

**Comment by Sammekl** [comment]
@Korazy Hi, yes we have tried that. This did not fix the problem

**Comment by Korazy** [comment]
Please feel free to reopen this issue if you run into it again :)
