### ISSUE TITLE
Manually linking is missing from docs :(

### ISSUE THREAD

**Issue by baxri** [Instabug/instabug-reactnative#175]
## UPDATE DOCS

I have some problem in automatic linking, it will greate this feature to add how to link this library manually to react native project. Almost every library has its guide to link packages manually.

Thanks in advance :)

**Comment by Korazy** [comment]
Hey @baxri 

Thanks for pointing this out. We will definitely check out the possibility if adding it :)

**Comment by lswank** [comment]
Seconding this only because many of us have internal policies not to use react-native link because of certain incompatibilities.

**Comment by Korazy** [comment]
Hey @lswank @baxri 

You can now find instructions for manual linking in our docs [here](https://docs.instabug.com/v1.0/docs/react-native-integration#section-manual-linking).
