### ISSUE TITLE
8.0.0 breaking changes?

### ISSUE THREAD

**Issue by sebirdman** [Instabug/instabug-reactnative#176]
Congrats on going from v2 to v8! Looks like this is an attempt to get things in line between all the library versions (so I'm excited). However, it looks like some things changed in the interfaces.

In particular, I'm seeing that startWithToken on iOS requires an array of invocation events now instead of a single invocation event. Changing this seems to have fixed my iOS builds.

Are there any other breaking changes we should be aware of?

**Comment by HeshamMegid** [comment]
We've done various API changes in version 8.0, but we've also maintained backward compatibility as much as we can, so you'll see lots of deprecated methods, and while they still work, they will be completely removed in a future release.

For the full details of the changes, please check our v8 [migration guide](https://docs.instabug.com/docs/react-native-migration-guide).
