### ISSUE TITLE
JSON value '2' of type NSNumber cannot be converted to NSArray

### ISSUE THREAD

**Issue by MaximilianLloyd** [Instabug/instabug-reactnative#178]
After i add this line: 
(with my key ofcourse)

```js
export class RootView extends Component {
  constructor () {
    super()
    Instabug.startWithToken('KEY', Instabug.invocationEvent.screenshot);
  }

```

I get the following error

![screen shot 2018-07-23 at 15 03 03](https://user-images.githubusercontent.com/10583205/43078052-914a2bc4-8e89-11e8-96c2-d9592718292a.png)

**Comment by Korazy** [comment]
Hey @MaximilianLloyd 

Thanks for reaching out. On version 8.0 there was a change that requires you to pass the events as an array. For example, it would look something like this: `Instabug.startWithToken('KEY', [Instabug.invocationEvent.screenshot]);`

Please feel free to reopen this issue if this doesnt resolve it for you :)
