### ISSUE TITLE
Some locale and strings are missing in iOS

### ISSUE THREAD

**Issue by yongdamsh** [Instabug/instabug-reactnative#181]
* Korean locale is supported in the [iOS module](https://github.com/Instabug/instabug-reactnative/blob/master/ios/RNInstabug/InstabugReactBridge.m#L627). But it's not defined in the [locale constant](https://github.com/Instabug/instabug-reactnative/blob/master/index.js#L1192-L1210).

* Some strings don't match with iOS enums.
  - [`addScreenRecordingMessage`](https://github.com/Instabug/instabug-reactnative/blob/master/ios/RNInstabug/InstabugReactBridge.m#L667) is missing
  - [`cancelButtonText`](https://github.com/Instabug/instabug-reactnative/blob/master/index.js#L1302) does not exist

**Comment by Korazy** [comment]
Hey @yongdamsh 

Thanks for pointing this out, we'll get to work on a fix right away.

**Comment by Korazy** [comment]
Hey @yongdamsh 

This should now be fixed as of 8.0.3. Please feel free to reopen the issue if it still exists.

**Comment by yongdamsh** [comment]
@Korazy Thanks for the fix. 
But how do I change the string in the red box in the screenshot below? iOS seems to be supporting it [here](https://github.com/Instabug/instabug-reactnative/blob/master/ios/RNInstabug/InstabugReactBridge.m#L667). But it's not defined in `index.js`. Can the library support this string? Or I can make a PR.

![instabug_l10n](https://user-images.githubusercontent.com/4126644/43429363-eb408208-949d-11e8-94d9-cfdbe0f98ae4.png)
