### ISSUE TITLE
invokeWithInvocationModeAndOptions with BugReporting.invocationMode.NA doesn't work on Android

### ISSUE THREAD

**Issue by nikhilvavs** [Instabug/instabug-reactnative#186]
Calling BugReporting.invokeWithInvocationModeAndOptions(BugReporting.invocationMode.NA, [BugReporting.invocationOptions.emailFieldHidden]) fails on android.

BugReporting.invocationMode.NA maps to Instabug.invocationModeNA and **invocationModeNA** string is not defined in Android.  The following 4 are defined

1. INVOCATION_MODE_NEW_BUG
2. INVOCATION_MODE_NEW_FEEDBACK
3. INVOCATION_MODE_NEW_CHAT
4. INVOCATION_MODE_CHATS_LIST

The field is going as NULL and the comparision at instabug-reactnative/android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java:264 throws an error.
We should add the string for NA in Android.

**Comment by salmamali** [comment]
We just released a fix for this. Please update to version 8.0.5.
