### ISSUE TITLE
Welcome message with screenshot not customisable

### ISSUE THREAD

**Issue by nikhilvavs** [Instabug/instabug-reactnative#192]
The welcome message when the trigger is screenshot is not customizable. Only the following strings are changeable. Can we have a custom screenshot welcome message too?

1. Instabug.strings.shakeHint
2. Instabug.strings.swipeHint
3. Instabug.strings.edgeSwipeStartHint

**Comment by salmatarzi** [comment]
@FloSugar The path in the error that you shared states that the node_modules are inside the ios directory of the app. Did you perhaps npm install the package from the ios directory?

**Comment by rdiaa** [comment]
@nikhilvavs 
sorry for the late reply, I will check it and get back to you

**Comment by rdiaa** [comment]
@nikhilvavs 

This is fixed in V8.0.8. Please check it
