### ISSUE TITLE
Adding the Javascript frames to the crash reports’ stack trace.

### ISSUE THREAD

**Issue by shercoder** [Instabug/instabug-reactnative#2]
Currently, the stacktrace we get is useless when trying to track the problem in Javascript. It makes it difficult to reproduce the problem and harder to fix when we don't have Javascript stacktrace. 

Are there are any plans to support this in near future?

Currently I am trying to get the following solution working which I took from [https://github.com/mikelambert/react-native-fabric-crashlytics](react-native-fabric-crashlytics) and modified a bit to use with `Instabug`. But this isn't much helpful either since the stacktraces still come from the bundle file and it's useless. I am currently looking into adding sourcemap and see if that would be helpful. However, if this can supported out of the box in `instabug-reactnative` then that would be very helpful for Instabug users.

```Javascript
'use strict';

import { Platform } from 'react-native';
import StackTrace from 'stacktrace-js';
import Instabug from 'Instabug';

function init() {
	// if (__DEV__) {
	// 	// Don't send exceptions from __DEV__, it's way too noisy!
	// 	// Live reloading and hot reloading in particular lead to tons of noise...
	// 	return;
	// }

	const originalHandler = global.ErrorUtils.getGlobalHandler();
	function errorHandler(e, isFatal) {
		StackTrace.fromError(e, {offline: true}).then((x) => {
			const result = x.map((row) => {
				return `functionName: ${row.functionName}\nsource: ${row.source}\nfileName:${row.fileName}:${row.lineNumber || 0}:${row.columnNumber || 0}\n`;
			});
                        Instabug.log(result.join('\n'));
			Instabug.reportException(e.message);
		});
		// And then re-throw the exception with the original handler
		if (originalHandler) {
			if (Platform.OS === 'ios') {
				originalHandler(e, isFatal);
			} else {
				// On Android, throwing the original exception immediately results in the
				// recordCustomExceptionName() not finishing before the app crashes and therefore not logged
				// Add a delay to give it time to log the custom JS exception before crashing the app.
				// The user facing effect of this delay is that separate JS errors will appear as separate
				// issues in the Crashlytics dashboard.
				setTimeout(() => {
					originalHandler(e, isFatal);
				}, 500);
			}
		}
	}
	global.ErrorUtils.setGlobalHandler(errorHandler);
}

module.exports = {
	init,
};

```

**Comment by yousefhamza** [comment]
Thanks for your feedback we highly appreciate it, We have looked into it and will consider it for future development.

**Comment by jozan** [comment]
JS stacktrace is quite important for us as well. I would like to see them in the future releases!

**Comment by salmatarzi** [comment]
@jozan @shercoder I know this issue has been here for a long time, and I really apologise for that. Update: We are currently working on supporting JS stacktraces, and hopefully it will be released by the end of September.

**Comment by SudoPlz** [comment]
That's the only reason I'm also using BugSnag right now.
If you guys implement javascript stack trace (w/ deobfuscation) I'd definitely prefer using your tool for bugs.

**Comment by NadineMansour** [comment]
@shercoder I renamed the issue to help other people identify the topic more quickly.

**Comment by jozan** [comment]
@salmatarzi Hello! Do you know is the support for JS stacktraces still on your priority list?

**Comment by salmatarzi** [comment]
@jozan Hey! Yes, it's on the top of our priority list. It's what we're currently working on right now. I will update you when it gets released.

**Comment by jozan** [comment]
Good to hear! :)

**Comment by RWOverdijk** [comment]
I can 👍 this. Bugsnag does this beautifully. You can even upload a source map to get readable stacktraces! Of course, it doesn't have the awesome feedback feature.

**Comment by salmatarzi** [comment]
@RWOverdijk  @jozan @SudoPlz @shercoder JS stack traces is now supported on version 2.11.0 ✨🎉

**Comment by RWOverdijk** [comment]
@salmatarzi Cool! Blog post?

**Comment by SudoPlz** [comment]
- Also does it work for both iOS and Android?
- And do we have to upload sourcemaps?
