### ISSUE TITLE
Some issues with release v1.0.6

### ISSUE THREAD

**Issue by yloeza** [Instabug/instabug-reactnative#20]
@DevHossamHassan Hey, thanks for releasing a new version containing some of my fixes, I wanted to give it a try but I found some issues.

One of the changes made on this version was fixing a typo of a bridge instabug function `setPostInvocationHandler`. I was looking at the documentation but apparently it has not been updated since still has typo in the name (https://instabug.com/public/ios-api-reference/Classes/Instabug.html#//api/name/setPostInvocatioHandler:)

Instabug released that typo on version 6.1.1
https://github.com/Instabug/Instabug-iOS/blob/5671d11a43b527f69e501e2853e74114e3054afc/Instabug.framework/Versions/A/Headers/Instabug.h#L227

So I tried to update my pod version to 6.1.1, but that version does not longer exposes `IBGEnums.h`
which is used here: https://github.com/Instabug/instabug-reactnative/blob/master/ios/RNInstabug/RCTConvert%2BInstabugEnums.m#L10

Also not sure if the way we import instabug here https://github.com/Instabug/instabug-reactnative/blob/master/ios/RNInstabug/InstabugReactBridge.m#L8 was intentional, I'm not able to have a successful build since Instabug is not found.

**Comment by DevHossamHassan** [comment]
Hey @yloeza,
Thanks for reporting these issues we really appreciate that.
We are fixing them and will get back to you ASAP.

By the way, we have just released the latest features we have been working on for the past month. 
Read more at: http://blog.instabug.com/2017/02/instabug-february-updates/

**Comment by yloeza** [comment]
Awesome! .. thanks for updates reference.

**Comment by pelle** [comment]
We're having these same issues as well

**Comment by yousefhamza** [comment]
@yloeza, @pelle I pushed some fixes that will fix your problems (Make sure to update your pods as well to version 7.0)!

**Comment by yloeza** [comment]
Thanks! I was able to successfully build and test the fixes.
