### ISSUE TITLE
Instabug.invoke() doesn't seem to work on Android.

### ISSUE THREAD

**Issue by booboothefool** [Instabug/instabug-reactnative#28]
I am able to get the floating button to work, but I would like to use my own button with `Instabug.invoke()`. When called, the prompt options doesn't appear. This is only on Android. iOS is working great.

```
new RNInstabugReactnativePackage("my_key", MainApplication.this, "button"),
```
^ Floating blue button appears, pressing it shows the prompt options.

but

```
new RNInstabugReactnativePackage("my_key", MainApplication.this, "none"),
```
then 
```
<Button
  onPress={() => Instabug.invoke()}
/>
```
^ Nothing appears when button is pressed. (Same button works on iOS).

If I understood the setup instructions correctly, iOS requires `        Instabug.startWithToken(Config.INSTABUG_TOKEN_IOS, Instabug.invocationEvent.none)`, but Android does not (and the floating button works anyway, just not the manual invoke).

**Comment by DevHossamHassan** [comment]
Hello @booboothefool,
Thank you for reporting this, That's weird we'll check it and we will get back to you as soon as possible.

**Comment by booboothefool** [comment]
@DevHossamHassan Sorry, but it seems like there's more to it!

```
<Button
  onPress={() => Instabug.invoke()}
/>
```
^ This actually works. Sorry, I didn't test it earlier. I was actually doing this.

```
  confirmIssuesFeedback() {
    const message = 'If reporting a bug, please provide clear steps to reproduce the bug.';

    Alert.alert('Issues/Feedback', message, [
      { text: 'Got It', onPress: () => Instabug.invoke() },
      { text: 'Cancel', onPress: () => {}, style: 'cancel' },
    ]);
  }

<Button
  onPress={() => this.confirmIssuesFeedback()}
/>
```

For some reason, when using an Alert to invoke, it will not show. Not a big deal however, as I could do without the Alert and just invoke from button. This does work in iOS, however.

**Comment by booboothefool** [comment]
Hi, so I discovered the issue is not Alert. It's that I need to call invoke twice for some reason e.g.

```
Instabug.invoke();  // doesn't show
Instabug.invoke();  // shows
```

**Comment by seantimm** [comment]
I'm seeing the same issue.
