### ISSUE TITLE
Android Instabug.setUserName('username') is not a function

### ISSUE THREAD

**Issue by booboothefool** [Instabug/instabug-reactnative#29]
Clearly it's there... but I get an error when I try to use it like `Instabug.setUserName('username')`. `Instabug.setUserData()`, `Instabug.setUserEmail()` work, however.

![screen shot 2017-04-28 at 2 10 07 pm](https://cloud.githubusercontent.com/assets/13257645/25541414/95a0fafc-2c1c-11e7-84c3-6265ec4ed782.png)

**Comment by booboothefool** [comment]
Hi, I found the issue.

In instabug-reactnative you added `setUserName`: https://github.com/Instabug/instabug-reactnative/blob/master/index.js#L207

but in the Android bridge it is actually `setUsername`: https://github.com/Instabug/instabug-reactnative/blob/master/android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java#L184

so I had to do this:
```
        if (Platform.OS === 'ios') {
          Instabug.setUserName(username);
        } else if (Platform.OS === 'android') {
          NativeModules.Instabug.setUsername(username);
        }
```

**Comment by DevHossamHassan** [comment]
Hello @booboothefool thank you for reporting this issue
This should be fixed. you may need to uninstall and reinstall the plugin to pull the fix.
Cheers
