### ISSUE TITLE
Android runtime exception: "Got unknown argument class: Locale"

### ISSUE THREAD

**Issue by sjyoung12** [Instabug/instabug-reactnative#3]
Hi there,

I'm getting the following exception immediately after retrieving the bundle from the packager (iOS works fine):
![screen shot 2017-01-06 at 5 04 10 pm](https://cloud.githubusercontent.com/assets/1925695/21737991/f3be2c72-d433-11e6-8ac6-3c899c5282a1.png)

Usage:
```
class App extends Component {

  constructor() {
    super();
    Instabug.startWithToken(process.env.INSTABUG_TOKEN, Instabug.invocationEvent.shake);
  }

```

According to the [React Native source](https://github.com/facebook/react-native/blob/911c05a89bbe86e9c805d7eee58cdfd66b80a64c/ReactAndroid/src/main/java/com/facebook/react/bridge/BaseJavaModule.java#L264), it does appear to be true that `Locale` is not a supported argument class.  Am I missing anything here?

Thanks in advance for any help or guidance!

RN version: 0.39
instabug-reactnative version: 1.0.2 (installed via `react-native link instabug-reactnative`)

**Comment by DevHossamHassan** [comment]
Hey @sjyoung12,
Thanks for reporting this issue.
We are looking into it and will inform you when we are done.
Cheers

**Comment by DevHossamHassan** [comment]
Hey @sjyoung12 
Please, update to Version 1.0.3 and let me know if you still facing any problems.

**Comment by sjyoung12** [comment]
@DevHossamHassan: thanks, that did the trick.  BTW, I think you forgot to bump the version number in your `package.json`. :)

**Comment by DevHossamHassan** [comment]
@sjyoung12  good catch. thank you 👍 
try it now, I updated the `package.json` file just now.
