### ISSUE TITLE
Random iOS crash?

### ISSUE THREAD

**Issue by booboothefool** [Instabug/instabug-reactnative#30]
Started getting this crash after integrating Instabug. It seems kind of random as I cannot reproduce it consistently, and I am unsure how to actually read this crash report, but it seems Instabug may potentially be linked to it. Any ideas?

![crash](https://cloud.githubusercontent.com/assets/13257645/25561236/6a960ae0-2d35-11e7-9508-7a46b0bbc692.png)

**Comment by booboothefool** [comment]
This is very similar to this http://stackoverflow.com/questions/31357028/ios-crash-libobjc-a-dylib-objc-msgsend, a bug in Crashlytics. Considering Instabug is similar, a bug/crash reporting service, could something be wrong?

**Comment by booboothefool** [comment]
Okay, yes.

I can confirm this crash is no longer happening after I removed:
`Instabug.startWithToken(Config.INSTABUG_TOKEN_IOS, Instabug.invocationEvent.shake);`

but I would like to use Instabug in my app. ;)

**Comment by yousefhamza** [comment]
Try editing the Podfile for getting the Instabug SDK to:
`pod 'Instabug', '~> 7.0'`
from:
`pod 'Instabug', '~> 7.0.0'`

**Comment by booboothefool** [comment]
@yousefhamza 

Those seem to both do the same thing? (use `nstabug 7.0.5`)

but I will try:
`pod 'Instabug', '7.0.0'`

**Comment by yousefhamza** [comment]
Use `pod 'Instabug', '~> 7.2'`

**Comment by yousefhamza** [comment]
Great 👍

**Comment by booboothefool** [comment]
@yousefhamza Hey sorry, I spoke a little too soon. The crash is still occurring. 😢

**Comment by yousefhamza** [comment]
Will look into it, If you have a project that reproduce the crash that would help quicken the process.

**Comment by salmatarzi** [comment]
@booboothefool Is this crash still occuring? If yes, then could you please symbolicate the crash, or tell us the steps that will lead to reproduce the crash?

**Comment by salmatarzi** [comment]
@booboothefool I will close this issue for now, if the problem is still there, feel free to reopen the issue.
