### ISSUE TITLE
Does logUserEventWithNameAndParams really exist?

### ISSUE THREAD

**Issue by SudoPlz** [Instabug/instabug-reactnative#33]
I saw you support `Instabug. logUserEventWithNameAndParams` but I don't see this implemented here?

http://docs.instabug.com/v5/docs/loggin-react
Am I mistaken or is this a feature not yet deployed?

Thanks.

**Comment by yousefhamza** [comment]
Hi this is yousef from Instabug team.

It's not deployed yet, scheduled this weak 👍

Thanks for your patience.

**Comment by SudoPlz** [comment]
Hey Yousef..!

Awesome, thanks for letting me know, that would be amazing..!

**Comment by calvinlang** [comment]
I'm still getting the React Native crash that: Instabug.logUserEventWithNameAndParams is not a function. Has this been implemented?
