### ISSUE TITLE
android: cannot find symbol mInstabug.setUserName(username);

### ISSUE THREAD

**Issue by jplanders** [Instabug/instabug-reactnative#36]
I saw in a closed issue and in a commit that you fixed the setUsername to be setUserName for consistency with iOS.  However, we are now seeing this gradle build error when building for Android:

cannot find symbol mInstabug.setUserName(username);

As seen here:

https://stackoverflow.com/questions/43932286/gradle-build-error-cannot-find-symbol-for-minstabug-setusernameusername

So I changed line 186 to the previous casing to get a successful build:

```
    /**
     * Sets the user name that is used in the dashboard's contacts.
     *
     * @param username
     */
    @ReactMethod
    public void setUserName(String username) {
        try {
186 >            mInstabug.setUsername(username);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

**Comment by jfvfrazao** [comment]
Same thing happening to me

**Comment by DevHossamHassan** [comment]
Hello @jplanders,
Thank you for reporting this, It will be released in minutes since we are not expecting to merge Dev branch soon, So we are releasing the fix right now.
