### ISSUE TITLE
Typo on iOS enums for InstabugEnums invocationModeNewFeedback

### ISSUE THREAD

**Issue by yloeza** [Instabug/instabug-reactnative#4]
Enum has a typo on the name is getting bridge to JS. So the value ends up been undefined in JS.
Then you can't use `invocationModeNewFeedback` for invoking Instabug.

https://github.com/Instabug/instabug-reactnative/blob/master/ios/RNInstabug/RCTConvert%2BInstabugEnums.m#L26

**Comment by DevHossamHassan** [comment]
Hi @yloeza,
Thanks for reporting this.
We've just fixed this typo, so please update to v1.0.4.

**Comment by yloeza** [comment]
There is another typo in the constantsToExport function: https://github.com/Instabug/instabug-reactnative/blob/master/ios/RNInstabug/InstabugReactBridge.m#L219 

FYI, All constants are broken for android since is not been implemented properly. See https://github.com/Instabug/instabug-reactnative/blob/master/android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java#L442

**Comment by DevHossamHassan** [comment]
There is a fix for that typo in dev repo /
and for the constants issue, we are looking into it and will get back to you.
By the way thank you reporting this and for the PR! 👍
