### ISSUE TITLE
RN Installation without cocoapods

### ISSUE THREAD

**Issue by pukeanddie** [Instabug/instabug-reactnative#45]
I have a React Native xcode project setup and due certain constrains (Realm DB) I am unable to use cocoapods. I've tried following your installation instructions and have tried to manually link the Instabug sdk after running `react-native link instabug-reactnative`.

My issue is that the project fails to build with an error that `Instabug/Instabug.h` file not found in InstabugReactBridge.m

**Comment by salmatarzi** [comment]
Hi @pukeanddie, you need to follow these steps to manually link the library after running ```react-native link instabug-reactnative``` 

1. Create a Frameworks folder in the ios directory of your project, and add the Instabug.framework file inside of it 
2. Open your Xcode project, open the General tab, and under the Embedded Binaries, add the Instabug.framework file from the directory you have just created.
