### ISSUE TITLE
Crash in Android (rx.exceptions.OnErrorNotImplementedException)

### ISSUE THREAD

**Issue by SudoPlz** [Instabug/instabug-reactnative#52]
I opened an issue here but I'm not 100% sure wether it's an android related problem or a react-native related problem.

https://github.com/Instabug/android-sample/issues/52

Please check it out and let me know.
I'm using `"instabug-reactnative": "1.1.8"`
Thank you

**Comment by salmatarzi** [comment]
@SudoPlz This is an Android related issue. Someone from our android team will follow up with you on the android sample issues channel, or via our support channel support@instabug.com :blush:
