### ISSUE TITLE
Andriod Instabug constants are not implemented.

### ISSUE THREAD

**Issue by yloeza** [Instabug/instabug-reactnative#6]
Constants for android are not been implemented as it is for iOS.

**Comment by yloeza** [comment]
@DevHossamHassan I'm trying to avoid the need of checking the platform for selecting the invocation mode.
```js
const invocationMode = Platform.OS === 'ios' ? Instabug.invocationMode.newFeedback : 'feedback';
Instabug.invokeWithInvocationMode(invocationMode);
```

I prefer to relay in library constants, in case it change the value of the constant for whatever reason. The only thing is preventing to just have the following line is that in andriod the constants are returning `undefined`.
```js
Instabug.invokeWithInvocationMode(Instabug.invocationMode.newFeedback);
```

**Comment by DevHossamHassan** [comment]
Thanks @yloeza for reporting this and for the PR as well, 
I have just merged the PR and it will be released soon stay tuned. 
Cheers :)

**Comment by yloeza** [comment]
Awesome, thanks!
