### ISSUE TITLE
Error when upgrading to 1.2.4 in Windows

### ISSUE THREAD

**Issue by juanamd** [Instabug/instabug-reactnative#63]
There seems to be an issue with a pod file when upgrading in windows (or at least with Android build only configured). This is the error after executing "yarn upgrade instabug-reactnative":

Command failed.
Exit code: 1
Command: C:\WINDOWS\system32\cmd.exe
Arguments: /d /s /c cd ../../ios && pod install
Directory: C:\Users\_[...]_\node_modules\instabug-reactnative
Output:
'pod' is not recognized as an internal or external command,
operable program or batch file.

**Comment by gvillenave** [comment]
+1
The post install script running Cocoapod install needs to only run on Mac, or be optional.

**Comment by NadineMansour** [comment]
@juanamd @gvillenave 
This issue has been fixed in 177cc852b1730977501dd580398aba9a61f7131c

Please, take a look at the steps mentioned [here](https://github.com/Instabug/instabug-reactnative#upgrading-guide).

**Comment by gvillenave** [comment]
@NadineMansour Thanks, upgrading to v2 worked.

**Comment by juanamd** [comment]
Yep now it works, thanks. Closing this issue.
