### ISSUE TITLE
Errors when validating an iOS release build after upgrading to 2.0.0

### ISSUE THREAD

**Issue by gvillenave** [Instabug/instabug-reactnative#67]
I just upgraded to v2.0.0 but I'm getting the following validation errors when trying to submit a release archive of my app to the app store:

iTunes Store operation failed.
Unsupported Architectures. The executable for Trybeo.app/Frameworks/Instabug.framework contains unsupported architectures '[x86_64, i386]'.

iTunes Store operation failed.
Invalid Mach-O Format. The Mach-O in bundle "Trybeo.app/Frameworks/Instabug.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(bitcode) and arm64(bitcode), while the nested bundle Mach-O contains X86_64ALL(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting.

iTunes Store operation failed.
Invalid Segment Alignment. The app binary at 'Trybeo.app/Frameworks/Instabug.framework/Instabug' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

iTunes Store operation failed.
The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.

This is blocking my production release, what should I do?
Xcode version: 8.3.3

**Comment by msoliman** [comment]
@gvillenave looks like you need to call the `strip-frameworks.sh` script that removes the simulator architectures from your app before submitting to the store.

Can you try adding a new "Run Script Phase" in your target's "Build Phases" and add the following snippet to it

```
bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Instabug.framework/Instabug.bundle/strip-frameworks.sh"
```

Let me know how it goes.

**Comment by gvillenave** [comment]
It solved the issue. Thanks! Can you update the documentation?

**Comment by msoliman** [comment]
@gvillenave sure will do. Thanks for the update

**Comment by caipivara** [comment]
Another way to solve it: http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/
