### ISSUE TITLE
Build Fail when i update React Native 0.48

### ISSUE THREAD

**Issue by MatthieuPeyrot** [Instabug/instabug-reactnative#69]
Hi i update to last version of react native and instabug and have this issue :

![screen shot 2017-09-04 at 11 07 34](https://user-images.githubusercontent.com/22000269/30019622-86867c2c-9161-11e7-95cd-9f91ffbf98b4.png)

**Comment by MatthieuPeyrot** [comment]
There is link related to the  issue : https://github.com/facebook/react-native/issues/15775

**Comment by MatthieuPeyrot** [comment]
I can build if i change #import "RCTBridgeModule.h" to #import <React/RCTBridgeModule.h>
 in the InstabugReactBridge.h

**Comment by reemalashry1** [comment]
Hey @MatthieuPeyrot sorry for the late reply here,

we will include the fix for this issue in our next release, I'll notify you when it's out.

**Comment by MatthieuPeyrot** [comment]
Thanks

**Comment by reemalashry1** [comment]
Hey @MatthieuPeyrot 
please check the fix for this issue in the new release here: f2a5890d0133c8c7a9a5d7a21ffc9c038e838698
