### ISSUE TITLE
com.facebook.react.JavaScript (14): EXC_BAD_ACCESS (code=1, address=0x1)

### ISSUE THREAD

**Issue by jfilter** [Instabug/instabug-reactnative#75]
When starting the app for iOS, I receive this error:
com.facebook.react.JavaScript (14): EXC_BAD_ACCESS (code=1, address=0x1)

For this line:
InstabugReactBridge.m:458 `IBGNSLog(compeleteLog, arg_list);`

**Comment by reemalashry1** [comment]
Hey @jfilter we have fixed the issue and released a new version that includes the fix, here: 9b67bad

**Comment by jfilter** [comment]
Works for me. Thanks!
