### ISSUE TITLE
Build fails on RN 0.48 and iOS 11

### ISSUE THREAD

**Issue by fforres** [Instabug/instabug-reactnative#77]
I'm getting some errors while trying to upgrade install 2.0.3 on RN 0.48.3 on an iOS device running iOS 11 on `InstabugReactBridge.m:461`

![image](https://user-images.githubusercontent.com/952992/30714867-c48dbf8a-9eea-11e7-8801-32351a2f5fe7.png)

Out of the 6 errors, 5 are fixable by an xcode suggestion
`Use of undeclared identifier 'IBGLogLevelTrace'; did you mean 'RCTLogLevelTrace'?`
`Use of undeclared identifier 'IBGLogLevelInfo'; did you mean 'RCTLogLevelInfo'?`
`Use of undeclared identifier 'IBGLogLevelWarning'; did you mean 'RCTLogLevelWarning'?`
`Use of undeclared identifier 'IBGLogLevelError'; did you mean 'RCTLogLevelError'?`
`Use of undeclared identifier 'IBGLogLevelFatal'; did you mean 'RCTLogLevelFatal'?`

There is one error that is:
`Implicit declaration of function 'IBGNSLogWithLevel' is invalid in C99`

![image](https://user-images.githubusercontent.com/952992/30714942-156aeb6c-9eeb-11e7-8983-e11803a93045.png)

I came across this error by trying to upgrade to RN 0.48.3 with version 1.x and encountering the `Redefinition of RCTMethodInfo` error described here.
https://github.com/facebook/react-native/issues/15775 

Hopefully it helps

**Comment by fforres** [comment]
PS: You folks are still supporting 1.x? 
I created the pr with fix for 1.x version to support RN 0.48.3 but could not figure out if there was maybe a branch to keep supporting it? 
Anyways, it's here but I closed it -> https://github.com/Instabug/instabug-reactnative/pull/78/files

**Comment by reemalashry1** [comment]
Hey @fforres 
I just need to make sure, are you following the #upgrading-guide when upgrading from version 1.x.x to version 2.0.3, you can find that here: 584befd35459bf3b99677c7abe18953779f7b13a

Regarding  the PR for supporting version 1.x, I'll be checking this with the team and will get back to you about it 👍

**Comment by SaraChicaD** [comment]
We had the same issue and had to comment out Instabug just to get our app to run. Would love an update on this! Thanks for your hard work on this package!

**Comment by reemalashry1** [comment]
Hey @SaraChicaD are you following the [Upgrade Guide] when upgrading from version 1.x.x to version 2.0.3, you can find that here: 584befd ?

**Comment by SaraChicaD** [comment]
hi @reemalashry1 so i never updated, I installed 2 first. It just fails on iOS 11, but still works on Android? Thanks for your prompt reply!

**Comment by reemalashry1** [comment]
Hey @SaraChicaD this seems to be a different error, we will be checking this and I'll get back to you 😊

**Comment by ZiadAyman** [comment]
Hey @fforres are you still experiencing any problems now or shall I close this issue? :)

**Comment by fforres** [comment]
Sure @ZiadAyman  :) 
NP

**Comment by ZiadAyman** [comment]
Perfect! 

Don't hesitate to get back whenever you need any help :)
