### ISSUE TITLE
Installing Xcodeproj gem

### ISSUE THREAD

**Issue by juanamd** [Instabug/instabug-reactnative#79]
Lately I upgraded an app for iOS from version 1.x to 2.0.5 and had quite a lot of issues. After a long time iI discovered that I was missing the xcodeproj gem which is required by the linking ruby script.
As the error atm prints only "xcodeproj doesn't exist", at first I thought it refered to a file or folder which it was unable to find, or something similar, which made it quite hard to exactly tell what was wrong.

This got solved once I ran the command: `gem install xcodeproj`

I would suggest 2 improvements from my experience:
- To explicetely include the step of installing the xcodeproj gem in the migration guide.
- To improve the error message in the script so its more actionable (something like: "xcodeproj gem doesn't exist. Please run 'gem install xcodeproj' to install it, and re-run 'react-native link instabug-reactnative' again"

**Comment by reemalashry1** [comment]
Hey @juanamd 
Thank you for your feedback 👍 
Both the integration guide and the improved error message have been updated here 4ab8e827e19f537a2ad1410dc83378a9c9a862bf
