### ISSUE TITLE
EXC_BAD_ACCESS in InstabugReactLogFunction

### ISSUE THREAD

**Issue by eliperkins** [Instabug/instabug-reactnative#82]
I came across the same issue as reported in https://github.com/Instabug/instabug-reactnative/issues/77#issuecomment-335014604.

The issue is that since `InstabugReactLogFunction` is not a variadic function, `va_list arg_list` is null here: https://github.com/Instabug/instabug-reactnative/blob/7cc7e90/ios/RNInstabug/InstabugReactBridge.m

It looks like the implementation of `IBGNSLogWithLevel` expects this to be non-null, but I can't check that since the iOS SDK is closed source 😢 

I would recommend not using `va_list` here, since it will always be null, and thus provides no value.

**Comment by SaraChicaD** [comment]
hi @reemalashry1 any updates? thanks so much!!

**Comment by seantimm** [comment]
Same problem here.

**Comment by reemalashry1** [comment]
@SaraChicaD @seantimm We are on it, I'll get back to you about it today (hopefully 😀) 
Thank you for your patience!
