### ISSUE TITLE
Let the User disable and enable Instabug

### ISSUE THREAD

**Issue by jfilter** [Instabug/instabug-reactnative#84]
I want to give the user the option to disable Instabug or at least that it does not get invoked on shake. Is it even possible? On iOS, I could just check for the preference when the App launches but how do I do it on Android?

**Comment by reemalashry1** [comment]
Hey @jfilter for Android you can use `Instabug.disable()` 
Do you mind sharing what you do for iOS?

**Comment by jfilter** [comment]
Thanks. Here's my code for iOS. The preference only takes effect when the user restarts the app but it works.
```js
class iOSApp extends React.Component {
  async componentWillMount() {
    const inAppReporting = await AsyncStorage.getItem(
      '@inAppBugReportingEnabled'
    );
    
    if (inAppReporting === null || inAppReporting === 'true') {
      Instabug.startWithToken(InstabugIosId, Instabug.invocationEvent.shake);
      Instabug.setPromptOptionsEnabled(false, true, false);
      Instabug.setIntroMessageEnabled(false);
    }
  }

  render() {
    return <App />;
  }
}

AppRegistry.registerComponent('X', () => iOSApp);
```

**Comment by jfilter** [comment]
For Android, I couldn't make it work with `.disable()` so I set the threshold to an unreachable value:
```
Instabug.setShakingThresholdForAndroid(10000)
```
