### ISSUE TITLE
Why Android needs native init when iOS works in JS ?

### ISSUE THREAD

**Issue by wynch** [Instabug/instabug-reactnative#89]
Hello,

I was wondering why android integration needs to be done on the native side - in Application / java file - when iOS integration only needs Javascript ? Why the difference ?

**Comment by reemalashry1** [comment]
Hey  @wynch 
what happens is that Android needs to get initialized in the application class and cannot be initialized in an activity to avoid unexpected behaviors, we are currently working on unifying the initializing experience between Android and iOS :)
